<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-LANNSOB" failures="0" tests="2" name="Testing.TestCaseScreenshot" time="20.340" errors="1" timestamp="2023-10-21T15:55:22 IST" skipped="0">
  <testcase classname="Testing.TestCaseScreenshot" name="failtestcase" time="1.051">
    <error message="Method Testing.TestCaseScreenshot.failtestcase() didn&#039;t finish within the time-out 1000" type="org.testng.internal.thread.ThreadTimeoutException">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method Testing.TestCaseScreenshot.failtestcase() didn't finish within the time-out 1000
at java.base@17.0.7/java.lang.ProcessImpl.waitForInterruptibly(Native Method)
at java.base@17.0.7/java.lang.ProcessImpl.waitFor(ProcessImpl.java:566)
at app//org.openqa.selenium.manager.SeleniumManager.runCommand(SeleniumManager.java:108)
at app//org.openqa.selenium.manager.SeleniumManager.getDriverPath(SeleniumManager.java:251)
at app//org.openqa.selenium.remote.service.DriverFinder.getPath(DriverFinder.java:27)
at app//org.openqa.selenium.edge.EdgeDriver.generateExecutor(EdgeDriver.java:70)
at app//org.openqa.selenium.edge.EdgeDriver.<init>(EdgeDriver.java:59)
at app//org.openqa.selenium.edge.EdgeDriver.<init>(EdgeDriver.java:55)
at app//org.openqa.selenium.edge.EdgeDriver.<init>(EdgeDriver.java:47)
at app//org.openqa.selenium.edge.EdgeDriver.<init>(EdgeDriver.java:43)
at app//Testing.TestCaseScreenshot.failtestcase(TestCaseScreenshot.java:37)
at java.base@17.0.7/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base@17.0.7/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base@17.0.7/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base@17.0.7/java.lang.reflect.Method.invoke(Method.java:568)
at app//org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at app//org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
at app//org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
at app//org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
at java.base@17.0.7/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base@17.0.7/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base@17.0.7/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base@17.0.7/java.lang.Thread.run(Thread.java:833)
]]>
    </error>
    <system-out>
      <![CDATA[My testcase started
My testcase failed]]>
    </system-out>
  </testcase> <!-- failtestcase -->
  <testcase classname="Testing.TestCaseScreenshot" name="passtestcase" time="19.289">
    <system-out>
      <![CDATA[My testcase started
My testcase passed]]>
    </system-out>
  </testcase> <!-- passtestcase -->
  <system-out>
    <![CDATA[My testcase started
My testcase failed
My testcase started
My testcase passed]]>
  </system-out>
</testsuite> <!-- Testing.TestCaseScreenshot -->
